# Generated by Django 5.1.7 on 2025-04-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_author',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
