# Generated by Django 5.1.7 on 2025-04-02 11:43

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blogs.models.user_blog_image_path),
        ),
    ]
